FROM centos:7

# yum update
RUN yum update -y

# basic installation
RUN yum -y install epel-release
RUN yum install -y npm

# we're done with yum 
RUN yum clean all && rm -rf /var/cache/yum

# gitbook install
# (allow global npm install in docker :-)
RUN npm install -g gitbook-cli

# do a blank install: we'll need to install again when we've got book.json
# (expect gitbook directory loaded into /shared)
RUN mkdir /shared
RUN (cd /shared/ && gitbook install)

# entrypoint script
COPY build.sh /
RUN chmod 755 /build.sh


ENV RUNNING_IN_DOCKER Yes


ENTRYPOINT ["/build.sh"]
